FROM    debian:bullseye
RUN		apt-get update && apt-get upgrade -y && apt-get install git nginx -y

COPY    default	/etc/nginx/sites-available/default
COPY    index.html /var/www/html/index.html

CMD ["nginx", "-g", "daemon off;"]